language: node_js
sudo: false

node_js:
  - "10"

cache:
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      script:
        - yarn install
        - yarn run bootstrap
        - yarn run test
    - stage: deploy
      script: yarn run build:docs
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: docs/_book
      on:
        branch: master
