language: node_js
sudo: false

node_js:
  - "10"

cache:
  directories:
  - node_modules

script:
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: gh-pages
  on:
    branch: master
